"""empty message

Revision ID: 0e2c6764c67d
Revises: 7ec2eae566c5
Create Date: 2020-05-03 21:14:41.319666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e2c6764c67d'
down_revision = '7ec2eae566c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stonepaperscissor', sa.Column('xMove', sa.String(), nullable=True))
    op.add_column('stonepaperscissor', sa.Column('yMove', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stonepaperscissor', 'yMove')
    op.drop_column('stonepaperscissor', 'xMove')
    # ### end Alembic commands ###
