"""empty message

Revision ID: 7ec2eae566c5
Revises: 
Create Date: 2020-05-03 17:12:30.294767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ec2eae566c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stonepaperscissor', sa.Column('xScore', sa.Integer(), nullable=True))
    op.add_column('stonepaperscissor', sa.Column('yScore', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stonepaperscissor', 'yScore')
    op.drop_column('stonepaperscissor', 'xScore')
    # ### end Alembic commands ###
